### ISSUE TITLE
Fix issue where capitalized market name isn't found in market list

### ISSUE THREAD

**Issue by nazimamin** [YACHTPARTY/yachtbot#33]
We try to extract if there's a trade pair with the given command. i.e "$ETH binance USD"  or "$ETH binance usd"

Currently markets in https://github.com/YACHTPARTY/yachtbot/blob/d608e80b0ae63cf5723bdddd1f0f14baa0e9a457/src/market.js#L8 are lowercase, but given trade pair can be all in uppercase hence https://github.com/YACHTPARTY/yachtbot/blob/d608e80b0ae63cf5723bdddd1f0f14baa0e9a457/src/index.js#L52 check will fail. 

TODO: check tradepair as lowercase

**Comment by MuhsinunCool** [comment]
What exactly is the definition of this issue? Are you saying that these commands don't work?
$gas btc binance
$gas BtC bINanCE
$GAS BTC BINANCE

They work in my fork. Did I understand the issue correctly?
