### ISSUE TITLE
ENH-10007 Lock dependency versions

### ISSUE THREAD

**Issue by edreesjalili** [YACHTPARTY/yachtbot#49]
To prevent the project from breaking due to dependency API updates, we should lock in version numbers for the dependencies in package.json.

**Comment by nazimamin** [comment]
@edreesjalili doesn't npm auto*magic*ally do this?

**Comment by edreesjalili** [comment]
Yeah you're right, forgot about the package-lock.json. It seems that someone has it ignored in gitignore atm so we should probably fix that.

**Comment by numaer** [comment]
so the resolution of this would to essentially remove package-lock.json from .gitignore

**Comment by edreesjalili** [comment]
Yup
